### ISSUE TITLE
Running git executive from vs git.path config

### ISSUE THREAD

**Issue by JefferyLondon** [Nimaoth/VsCodePrefSync#1]
Hi,

Thank you for the plugin. As a enterprise user, I can’t login to github and can open sync the vs setting to internal git repo. 

Your plugin reminds me of pycharm’s famous `setting repository` plugin.

There is one issue here I would like to submit: VS code doesn’t recognise my installed git, therefore I have to manually specify the path of the git installation using `git.path`. could you please honors the config and use git executive from `git.path`?

Thank you very much
Jeffery

**Comment by Nimaoth** [comment]
Hi, sorry I totally forgot about this issue. I just added this feature in 1.0.4
