### ISSUE TITLE
Error: fatal: ambiguous argument '@{u}'

### ISSUE THREAD

**Issue by orgi** [Nimaoth/VsCodePrefSync#2]
Thanks for picking up this idea. I really appreciate it. Unfortunately whenever I try to upload the settings I get the following error message. You have any clue what this could be?
Maybe it is related to the git version (git version 2.21.0.windows.1)?

```
[Upload settings] Error occured: Error: fatal: ambiguous argument '@{u}': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]'
```

**Comment by orgi** [comment]
After the first manual push to the remote (creating the master branch on the remote) the error finally disappeared. However now I get:
```
[Upload settings] Error occured: TypeError: Cannot read property 'trim' of null
```

**Comment by orgi** [comment]
That's strange: As soon as I run VsCodePrefSync from within the debugger everything works like a charm. Back to VsCode it's still broken.

**Comment by Nimaoth** [comment]
This error seems to happen when the extension tries to figure out wether your local repository is behind or ahead of the remote repository, or wether it diverged or is up to date. 
The extension runs the following git commands:
```
git rev-parse "@"
git rev-parse "@{u}"
git merge-base "@" "@{u}"
```
These commands shoud each print the hash of a commit to standard out which the extension then reads in and compares to each other.
`git rev-parse "@"` should print the hash of HEAD.
`git rev-parse "@{u}"` shoud print the hash of the latest commit on the remote tracking branch of the current branch (so origin/master in your case)
`git merge-base "@" "@{u}"` shoud print the hash of the latest common ancestor of HEAD and the last commit on origin/master
It seems like one of these commands didn't output anything. Can you

**Comment by orgi** [comment]
Thanks for the quick answer. Unfortunately all three of them are working when running in the command line:
```
PS C:\repositories\vscode-settings> git rev-parse "@"
68b83cd719e3fcc6c059f64d2555bb3509d85177
PS C:\repositories\vscode-settings> git merge-base "@" "@{u}"
68b83cd719e3fcc6c059f64d2555bb3509d85177
PS C:\repositories\vscode-settings> git merge-base "@" "@{u}"
68b83cd719e3fcc6c059f64d2555bb3509d85177
```
That's as well what I noticed before opening this ticket. I have to PCs, both running Windows10. Initially I got the error on both machines. When debugging the VsCodePrefSync plugin in vscode I could step through those three lines and everything worked. Before that it didn't work. In addition I temporarily updated my local copy of VsCodePrefSync to use the latest version of SimpleGit. Somehow after that I got it working. It now still works even when using the older SimpleGit and without running in the debugger.
But on the other machine the error is still there. I'll try to run it in the debugger there as well to see what's happening.

Will keep you posted.

**Comment by orgi** [comment]
Finally I was able to get the vscode debugger running on my desktop as well.
* First thing I noticed was that the local repository currently cannot be configured using the configuration - the respective lines were commented (extensions.ts:170 ff).

```ts
    config.url = vscodeprefsync.get("repositoryUrl") as string;
    if (config.url === null || config.url === undefined || config.url === "") {
        vscode.window.showErrorMessage("Please provide the setting 'vscodeprefsync.repositoryUrl'");
        config.ok = false;
    }
```

* After uncommenting I was able to get things running when running from within the vscode debugger. When stepping through the 3 `trim()` calls everything seems to be fine.
* However after installing the build and running vscode (and the plugin) as a user I still get the same error
So maybe there's some kind of race condition where the either git does not return anything or where the  string returned from the git binary does not arrive in time.

**Comment by Nimaoth** [comment]
Sorry for the late response. I couldn't reproduce the issue, so I just added some exception handling in 1.0.4, so the extension should try to upload your settings even if this error occurs.

**Comment by orgi** [comment]
Same here: Sorry for the late response - and thanks for the fix. It *seems* like the error is gone. However I now get errors like

> [Download settings] Your local settings have diverged from the remote repository. There is nothing I can do.

Not sure how to resolve that one. I tried already merging the `settings.json` manually. However the error is still there...

**Comment by Nimaoth** [comment]
I just released a new version which should hopefully fix this problem, but since I can't reproduce this issue I don't know for sure.

**Comment by orgi** [comment]
@Nimaoth Thanks for the fix and sorry for the late feedback. However everything seems to be working now :)
So I'll close this ticket.

Thanks for the fast support 👍
